library(tidyverse)

# this script is for cleaning up the vcf output generated by matti's pipeline. here we specifically remove entries that don't contain "*" and 
# do a bit of a reorganization. 

# user defined vars
path_somatic <- "/groups/wyattgrp/users/amunzur/mt-ctDNA/WGS/variant_calling/matti_pipeline_results/somatic.vcf"
path_output <- "/groups/wyattgrp/users/amunzur/mt-ctDNA/WGS/variant_calling/matti_pipeline_results/somatic_cleaned.csv"

somatic <- as.data.frame(read_delim(path_somatic, delim = "\t"))
somatic <- pivot_longer(data = somatic, cols = starts_with("RG"), # put into long format, easier to parse and understand.
						names_to = "sample_names", 
						values_to = "variants")

to_keep <- grep("[*]", somatic$variants) # keep the rows with the asterix only
somatic <- somatic[to_keep, ]

write_csv(somatic, path_output)